//+------------------------------------------------------------------+
//|                                                  GridLayerEA.mq5 |
//|                                       Generated by Google Gemini |
//+------------------------------------------------------------------+
#property copyright "Generated by AI"
#property link      ""
#property version   "1.25"

#include <Trade\Trade.mqh>
#include <Trade\PositionInfo.mqh>
#include <Trade\OrderInfo.mqh>

enum ENUM_ORDER_CHOICE
{
    USE_LIMIT_ORDERS = 0, // Limit Orders (Catch Pullbacks)
    USE_STOP_ORDERS = 1   // Stop Orders (Follow Breakouts)
};

enum ENUM_FILTER_CHOICE
{
    FILTER_ATR = 0,   // ATR Only (Volatility / Candle Size)
    FILTER_ADX = 1,   // ADX Only (Trend Strength)
    FILTER_BOTH = 2   // Use BOTH (Safest for Gold M1)
};

//--- SECURITY & LICENSE INPUTS (Injected automatically by GitHub Actions)
input long   InpCustomAccount = 0;
input string InpExpiryDate    = "2026.12.31";
input string InpLicenseKey    = "N/A";

//--- Input Parameters
input ENUM_ORDER_CHOICE  OrderTypeChoice   = USE_LIMIT_ORDERS; // Order Strategy
input ENUM_FILTER_CHOICE VolatilityFilter  = FILTER_BOTH;      // Safety Filter Mode

input double LotSize               = 0.01;  // Starting Lot Size
input double LotStep               = 0.01;  // Lot size added per layer
input int    DistanceToFirstPoints = 500;   // Distance to 1st order (in Points)
input int    DistanceBetweenPoints = 300;   // Distance between layers (in Points)
input int    MaxGapDistance        = 800;   // Max gap before resetting orders (Points)
input double BaseProfitTarget      = 2.0;   // $2 base target per layer

//--- ATR SETTINGS (Used if Filter = ATR or BOTH) ---
input int    ATR_Period            = 14;    // ATR Period
input double ATR_ObserveLevel      = 150.0; // ATR >= Observe: Suspend new layers (Pts)
input double ATR_EmergencyLevel    = 300.0; // ATR >= Emergency: Force Close ALL (Pts)

//--- ADX SETTINGS (Used if Filter = ADX or BOTH) ---
input int    ADX_Period            = 14;    // ADX Period
input double ADX_ObserveLevel      = 25.0;  // ADX >= Observe: Suspend new layers
input double ADX_EmergencyLevel    = 31.0;  // ADX >= Emergency: Force Close ALL

input ulong  MagicNumber           = 12345; // Magic Number

//--- Global Variables
CTrade         trade;
CPositionInfo  posInfo;
COrderInfo     orderInfo;

int atrHandle = INVALID_HANDLE;
int adxHandle = INVALID_HANDLE;

double currentATR = 0.0;
double currentADX = 0.0;

int BuyPositions = 0;
int SellPositions = 0;
int BuyLimits = 0;
int SellLimits = 0;
double BuyProfit = 0.0;
double SellProfit = 0.0;
double CurrentBuyTarget = 0.0;
double CurrentSellTarget = 0.0;
double BuyTotalLots = 0.0;
double SellTotalLots = 0.0;

bool XRayPrinted = false;
bool ManualPause = false;             // Flag for the manual Start/Stop button
bool AutoEmergencyPause = false;      // Flag for automatic filter suspension
bool IsGridSuspended = false;         // Flag to suspend new orders in OBSERVE mode
bool EmergencyCloseTriggered = false; // Persistent flag to ensure everything closes

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
{
    // License validation check (Skips if InpCustomAccount is 0 for testing)
    if(InpCustomAccount != 0 && AccountInfoInteger(ACCOUNT_LOGIN) != InpCustomAccount)
    {
        Alert("LICENSE ERROR: This EA is licensed for account #", InpCustomAccount, " only.");
        return(INIT_FAILED);
    }

    if(AccountInfoInteger(ACCOUNT_MARGIN_MODE) != ACCOUNT_MARGIN_MODE_RETAIL_HEDGING)
    {
        Alert("ERROR: This Grid EA requires a HEDGING account.");
        return(INIT_FAILED);
    }

    if(VolatilityFilter == FILTER_ATR || VolatilityFilter == FILTER_BOTH)
    {
        atrHandle = iATR(_Symbol, PERIOD_CURRENT, ATR_Period);
        if(atrHandle == INVALID_HANDLE) Print("ERROR: Failed to create ATR handle.");
    }
    
    if(VolatilityFilter == FILTER_ADX || VolatilityFilter == FILTER_BOTH)
    {
        adxHandle = iADX(_Symbol, PERIOD_CURRENT, ADX_Period);
        if(adxHandle == INVALID_HANDLE) Print("ERROR: Failed to create ADX handle.");
    }

    trade.SetExpertMagicNumber(MagicNumber);
    ManualPause = false; 
    AutoEmergencyPause = false;
    IsGridSuspended = false;
    EmergencyCloseTriggered = false;
    CreateDashboard();
    return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
    if(atrHandle != INVALID_HANDLE) IndicatorRelease(atrHandle);
    if(adxHandle != INVALID_HANDLE) IndicatorRelease(adxHandle);
    ObjectsDeleteAll(0, "Dash_");
}

//+------------------------------------------------------------------+
//| Chart Event function (Handles Button Clicks)                     |
//+------------------------------------------------------------------+
void OnChartEvent(const int id, const long &lparam, const double &dparam, const string &sparam)
{
    if(id == CHARTEVENT_OBJECT_CLICK)
    {
        if(sparam == "Dash_Btn_StartStop")
        {
            ManualPause = !ManualPause;
            
            // Reset button state visually so it doesn't stay stuck pressed
            ObjectSetInteger(0, "Dash_Btn_StartStop", OBJPROP_STATE, false); 
            
            if(ManualPause) Print("Bot manually PAUSED by user.");
            else Print("Bot manually STARTED by user.");
            
            UpdateDashboard();
        }
    }
}

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
{
    // Update active filter values
    double buf[1];
    if(atrHandle != INVALID_HANDLE && CopyBuffer(atrHandle, 0, 0, 1, buf) > 0)
        currentATR = buf[0] / _Point; 
        
    if(adxHandle != INVALID_HANDLE && CopyBuffer(adxHandle, 0, 0, 1, buf) > 0)
        currentADX = buf[0];
    
    CountTrades();
    
    if(!XRayPrinted) 
    {
        RunXRayDiagnosis();
        XRayPrinted = true;
    }
    
    // Check emergency state to handle automatic pauses and closures
    ManageEmergencyClose();
    
    // If the bot is manually paused OR automatically paused by an emergency, skip trading
    if(ManualPause || AutoEmergencyPause || EmergencyCloseTriggered) 
    {
        UpdateDashboard();
        return; 
    }

    ManageGridSuspension(); 
    
    ManageGaps(); 
    CalculateTargets();
    ManageClosures();
    ManageMiddleClosure();
    
    CountTrades(); 
    ManageGrid();
    UpdateDashboard();
}

//+------------------------------------------------------------------+
//| FILTER LOGIC: Check Emergency State                              |
//+------------------------------------------------------------------+
bool IsEmergencyTriggered()
{
    bool atrEmergency = (VolatilityFilter == FILTER_ATR || VolatilityFilter == FILTER_BOTH) && (currentATR >= ATR_EmergencyLevel);
    bool adxEmergency = (VolatilityFilter == FILTER_ADX || VolatilityFilter == FILTER_BOTH) && (currentADX >= ADX_EmergencyLevel);
    return (atrEmergency || adxEmergency);
}

//+------------------------------------------------------------------+
//| FILTER LOGIC: Check Observe State                                |
//+------------------------------------------------------------------+
bool IsObserveTriggered()
{
    bool atrObserve = (VolatilityFilter == FILTER_ATR || VolatilityFilter == FILTER_BOTH) && (currentATR >= ATR_ObserveLevel);
    bool adxObserve = (VolatilityFilter == FILTER_ADX || VolatilityFilter == FILTER_BOTH) && (currentADX >= ADX_ObserveLevel);
    return (atrObserve || adxObserve);
}

//+------------------------------------------------------------------+
//| LOGIC: Emergency Close & Auto-Resume                             |
//+------------------------------------------------------------------+
void ManageEmergencyClose()
{
    if(IsEmergencyTriggered())
    {
        if(!AutoEmergencyPause && (BuyPositions > 0 || SellPositions > 0 || BuyLimits > 0 || SellLimits > 0))
        {
            Print("!!! DUAL-FILTER EMERGENCY CLOSE TRIGGERED !!! Wiping all positions and orders.");
            EmergencyCloseTriggered = true;
        }
        AutoEmergencyPause = true; // Bot automatically pauses
    }
    else
    {
        if(AutoEmergencyPause && !EmergencyCloseTriggered)
        {
            Print("Emergency conditions have cleared. Auto-resuming operations.");
            AutoEmergencyPause = false; // Automatically unpause when safe
        }
    }

    if(EmergencyCloseTriggered)
    {
        if(BuyPositions > 0 || SellPositions > 0 || BuyLimits > 0 || SellLimits > 0)
        {
            CloseAllPositions(POSITION_TYPE_BUY);
            CloseAllPositions(POSITION_TYPE_SELL);
            DeletePendingOrders(0);
            DeletePendingOrders(1);
            CountTrades(); 
        }
        
        if(BuyPositions == 0 && SellPositions == 0 && BuyLimits == 0 && SellLimits == 0)
        {
            Print("Emergency close complete. All positions wiped.");
            EmergencyCloseTriggered = false; // Ready to resume when filters drop
        }
    }
}

//+------------------------------------------------------------------+
//| LOGIC: Suspend New Grids (Observe Mode)                          |
//+------------------------------------------------------------------+
void ManageGridSuspension()
{
    bool needsSuspension = IsObserveTriggered() && !IsEmergencyTriggered();

    if(needsSuspension)
    {
        if(!IsGridSuspended)
        {
            Print("Filter threshold breached (Observe Mode). Suspending NEW layers.");
        }
        IsGridSuspended = true;
    }
    else if(!IsEmergencyTriggered()) 
    {
        if(IsGridSuspended)
        {
            Print("Filters returned to normal. Grid operations RESUMING.");
            
            if(BuyPositions == 0 && SellPositions == 0)
            {
                DeletePendingOrders(0);
                DeletePendingOrders(1);
                CountTrades(); 
            }
        }
        IsGridSuspended = false;
    }
}

//+------------------------------------------------------------------+
//| DIAGNOSIS: X-Ray Scanner                                         |
//+------------------------------------------------------------------+
void RunXRayDiagnosis()
{
    Print("========== X-RAY DIAGNOSIS START ==========");
    PrintFormat("Symbol: %s | Mode: %s", _Symbol, (OrderTypeChoice==USE_LIMIT_ORDERS?"LIMIT":"STOP"));
    Print("========== X-RAY DIAGNOSIS END ==========");
}

//+------------------------------------------------------------------+
//| LOGIC: Count Active Positions and Pending Orders                 |
//+------------------------------------------------------------------+
void CountTrades()
{
    BuyPositions = 0; SellPositions = 0;
    BuyLimits = 0; SellLimits = 0;
    BuyProfit = 0.0; SellProfit = 0.0;
    BuyTotalLots = 0.0; SellTotalLots = 0.0;

    for(int i = PositionsTotal() - 1; i >= 0; i--)
    {
        if(posInfo.SelectByIndex(i) && posInfo.Symbol() == _Symbol && posInfo.Magic() == MagicNumber)
        {
            if(posInfo.PositionType() == POSITION_TYPE_BUY)
            {
                BuyPositions++;
                BuyProfit += posInfo.Profit() + posInfo.Swap() + posInfo.Commission();
                BuyTotalLots += posInfo.Volume();
            }
            else if(posInfo.PositionType() == POSITION_TYPE_SELL)
            {
                SellPositions++;
                SellProfit += posInfo.Profit() + posInfo.Swap() + posInfo.Commission();
                SellTotalLots += posInfo.Volume();
            }
        }
    }

    for(int i = OrdersTotal() - 1; i >= 0; i--)
    {
        if(orderInfo.SelectByIndex(i) && orderInfo.Symbol() == _Symbol && orderInfo.Magic() == MagicNumber)
        {
            if(orderInfo.OrderType() == ORDER_TYPE_BUY_LIMIT || orderInfo.OrderType() == ORDER_TYPE_BUY_STOP) BuyLimits++;
            else if(orderInfo.OrderType() == ORDER_TYPE_SELL_LIMIT || orderInfo.OrderType() == ORDER_TYPE_SELL_STOP) SellLimits++;
        }
    }
}

//+------------------------------------------------------------------+
//| LOGIC: Manage Gaps (Trailing pending orders)                     |
//+------------------------------------------------------------------+
void ManageGaps()
{
    if(IsGridSuspended) return;

    double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
    double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
    double maxGap = MaxGapDistance * _Point;

    if(BuyLimits > 0 && BuyPositions == 0)
    {
        double closestBuy = 0.0;
        for(int i = OrdersTotal() - 1; i >= 0; i--)
        {
            if(orderInfo.SelectByIndex(i) && orderInfo.Symbol() == _Symbol && orderInfo.Magic() == MagicNumber)
            {
                if(orderInfo.OrderType() == ORDER_TYPE_BUY_LIMIT || orderInfo.OrderType() == ORDER_TYPE_BUY_STOP)
                {
                    if(orderInfo.PriceOpen() > closestBuy) closestBuy = orderInfo.PriceOpen();
                }
            }
        }
        
        if(closestBuy > 0 && (ask - closestBuy) > maxGap)
        {
            DeletePendingOrders(0);
            BuyLimits = 0; 
        }
    }

    if(SellLimits > 0 && SellPositions == 0)
    {
        double closestSell = 9999999.0;
        for(int i = OrdersTotal() - 1; i >= 0; i--)
        {
            if(orderInfo.SelectByIndex(i) && orderInfo.Symbol() == _Symbol && orderInfo.Magic() == MagicNumber)
            {
                if(orderInfo.OrderType() == ORDER_TYPE_SELL_LIMIT || orderInfo.OrderType() == ORDER_TYPE_SELL_STOP)
                {
                    if(orderInfo.PriceOpen() < closestSell) closestSell = orderInfo.PriceOpen();
                }
            }
        }
        
        if(closestSell < 9999999.0 && (closestSell - bid) > maxGap)
        {
            DeletePendingOrders(1);
            SellLimits = 0; 
        }
    }
}

//+------------------------------------------------------------------+
//| LOGIC: Calculate Target (Additive: $2 per layer)                 |
//+------------------------------------------------------------------+
void CalculateTargets()
{
    if(BuyPositions > 0)
        CurrentBuyTarget = BaseProfitTarget * BuyPositions;
    else
        CurrentBuyTarget = BaseProfitTarget;

    if(SellPositions > 0)
        CurrentSellTarget = BaseProfitTarget * SellPositions;
    else
        CurrentSellTarget = BaseProfitTarget;
}

//+------------------------------------------------------------------+
//| LOGIC: Manage Standard Closures (Independent)                    |
//+------------------------------------------------------------------+
void ManageClosures()
{
    if(BuyPositions > 0 && BuyProfit >= CurrentBuyTarget)
    {
        CloseAllPositions(POSITION_TYPE_BUY);
        DeletePendingOrders(0); 
    }
    
    if(SellPositions > 0 && SellProfit >= CurrentSellTarget)
    {
        CloseAllPositions(POSITION_TYPE_SELL);
        DeletePendingOrders(1); 
    }
}

//+------------------------------------------------------------------+
//| LOGIC: Trapped Middle Price Closure (Combined)                   |
//+------------------------------------------------------------------+
void ManageMiddleClosure()
{
    if(BuyPositions > 0 && SellPositions > 0)
    {
        double highestBuy = GetHighestOpenPrice(POSITION_TYPE_BUY);
        double lowestSell = GetLowestOpenPrice(POSITION_TYPE_SELL);
        double currentBid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
        double currentAsk = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
        
        if(currentBid > highestBuy && currentAsk < lowestSell)
        {
            if((BuyProfit + SellProfit) > 0.0)
            {
                CloseAllPositions(POSITION_TYPE_BUY);
                CloseAllPositions(POSITION_TYPE_SELL);
                DeletePendingOrders(0);
                DeletePendingOrders(1);
            }
        }
    }
}

//+------------------------------------------------------------------+
//| HELPER Functions                                                 |
//+------------------------------------------------------------------+
void CloseAllPositions(ENUM_POSITION_TYPE type)
{
    for(int i = PositionsTotal() - 1; i >= 0; i--)
    {
        if(posInfo.SelectByIndex(i) && posInfo.Symbol() == _Symbol && posInfo.Magic() == MagicNumber && posInfo.PositionType() == type)
        {
            trade.PositionClose(posInfo.Ticket());
        }
    }
}

void DeletePendingOrders(int direction) 
{
    for(int i = OrdersTotal() - 1; i >= 0; i--)
    {
        if(orderInfo.SelectByIndex(i) && orderInfo.Symbol() == _Symbol && orderInfo.Magic() == MagicNumber)
        {
            if(direction == 0 && (orderInfo.OrderType() == ORDER_TYPE_BUY_LIMIT || orderInfo.OrderType() == ORDER_TYPE_BUY_STOP))
                trade.OrderDelete(orderInfo.Ticket());
            if(direction == 1 && (orderInfo.OrderType() == ORDER_TYPE_SELL_LIMIT || orderInfo.OrderType() == ORDER_TYPE_SELL_STOP))
                trade.OrderDelete(orderInfo.Ticket());
        }
    }
}

double GetLowestOpenPrice(ENUM_POSITION_TYPE type)
{
    double lowestPrice = 9999999.0;
    for(int i = PositionsTotal() - 1; i >= 0; i--)
    {
        if(posInfo.SelectByIndex(i) && posInfo.Symbol() == _Symbol && posInfo.Magic() == MagicNumber && posInfo.PositionType() == type)
        {
            if(posInfo.PriceOpen() < lowestPrice) lowestPrice = posInfo.PriceOpen();
        }
    }
    return lowestPrice;
}

double GetHighestOpenPrice(ENUM_POSITION_TYPE type)
{
    double highestPrice = 0.0;
    for(int i = PositionsTotal() - 1; i >= 0; i--)
    {
        if(posInfo.SelectByIndex(i) && posInfo.Symbol() == _Symbol && posInfo.Magic() == MagicNumber && posInfo.PositionType() == type)
        {
            if(posInfo.PriceOpen() > highestPrice) highestPrice = posInfo.PriceOpen();
        }
    }
    return highestPrice;
}

//+------------------------------------------------------------------+
//| LOGIC: Manage the Grid (Directional Limits & Stops)              |
//+------------------------------------------------------------------+
void ManageGrid()
{
    if(IsGridSuspended) return; 

    double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
    double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
    double distFirst = DistanceToFirstPoints * _Point;
    double distBetween = DistanceBetweenPoints * _Point;

    // BUY SIDE
    if(BuyLimits == 0)
    {
        if(BuyPositions == 0)
        {
            double startPrice = (OrderTypeChoice == USE_LIMIT_ORDERS) ? (ask - distFirst) : (ask + distFirst); 
            for(int i = 0; i < 5; i++)
            {
                double price = (OrderTypeChoice == USE_LIMIT_ORDERS) ? (startPrice - (i * distBetween)) : (startPrice + (i * distBetween));
                double currentLot = NormalizeDouble(LotSize + (i * LotStep), 2);
                
                if(OrderTypeChoice == USE_LIMIT_ORDERS) trade.BuyLimit(currentLot, price, _Symbol, 0.0, 0.0, ORDER_TIME_GTC, 0, "Grid Buy Limit");
                else trade.BuyStop(currentLot, price, _Symbol, 0.0, 0.0, ORDER_TIME_GTC, 0, "Grid Buy Stop");
            }
        }
        else 
        {
            double startPrice = (OrderTypeChoice == USE_LIMIT_ORDERS) ? (GetLowestOpenPrice(POSITION_TYPE_BUY) - distBetween) : (GetHighestOpenPrice(POSITION_TYPE_BUY) + distBetween);
            for(int i = 0; i < 5; i++)
            {
                double price = (OrderTypeChoice == USE_LIMIT_ORDERS) ? (startPrice - (i * distBetween)) : (startPrice + (i * distBetween));
                double currentLot = NormalizeDouble(LotSize + ((BuyPositions + i) * LotStep), 2);
                
                if(OrderTypeChoice == USE_LIMIT_ORDERS) trade.BuyLimit(currentLot, price, _Symbol, 0.0, 0.0, ORDER_TIME_GTC, 0, "Grid Buy Limit");
                else trade.BuyStop(currentLot, price, _Symbol, 0.0, 0.0, ORDER_TIME_GTC, 0, "Grid Buy Stop");
            }
        }
    }
    
    // SELL SIDE
    if(SellLimits == 0)
    {
        if(SellPositions == 0)
        {
            double startPrice = (OrderTypeChoice == USE_LIMIT_ORDERS) ? (bid + distFirst) : (bid - distFirst);
            for(int i = 0; i < 5; i++)
            {
                double price = (OrderTypeChoice == USE_LIMIT_ORDERS) ? (startPrice + (i * distBetween)) : (startPrice - (i * distBetween));
                double currentLot = NormalizeDouble(LotSize + (i * LotStep), 2);
                
                if(OrderTypeChoice == USE_LIMIT_ORDERS) trade.SellLimit(currentLot, price, _Symbol, 0.0, 0.0, ORDER_TIME_GTC, 0, "Grid Sell Limit");
                else trade.SellStop(currentLot, price, _Symbol, 0.0, 0.0, ORDER_TIME_GTC, 0, "Grid Sell Stop");
            }
        }
        else 
        {
            double startPrice = (OrderTypeChoice == USE_LIMIT_ORDERS) ? (GetHighestOpenPrice(POSITION_TYPE_SELL) + distBetween) : (GetLowestOpenPrice(POSITION_TYPE_SELL) - distBetween);
            for(int i = 0; i < 5; i++)
            {
                double price = (OrderTypeChoice == USE_LIMIT_ORDERS) ? (startPrice + (i * distBetween)) : (startPrice - (i * distBetween));
                double currentLot = NormalizeDouble(LotSize + ((SellPositions + i) * LotStep), 2);
                
                if(OrderTypeChoice == USE_LIMIT_ORDERS) trade.SellLimit(currentLot, price, _Symbol, 0.0, 0.0, ORDER_TIME_GTC, 0, "Grid Sell Limit");
                else trade.SellStop(currentLot, price, _Symbol, 0.0, 0.0, ORDER_TIME_GTC, 0, "Grid Sell Stop");
            }
        }
    }
}

//+------------------------------------------------------------------+
//| GUI Dashboard                                                    |
//+------------------------------------------------------------------+
void CreateLabel(string name, int x, int y, string text, color clr)
{
    ObjectCreate(0, name, OBJ_LABEL, 0, 0, 0);
    ObjectSetInteger(0, name, OBJPROP_XDISTANCE, x);
    ObjectSetInteger(0, name, OBJPROP_YDISTANCE, y);
    ObjectSetInteger(0, name, OBJPROP_CORNER, CORNER_LEFT_UPPER);
    ObjectSetString(0, name, OBJPROP_TEXT, text);
    ObjectSetInteger(0, name, OBJPROP_COLOR, clr);
    ObjectSetInteger(0, name, OBJPROP_FONTSIZE, 9);
    ObjectSetString(0, name, OBJPROP_FONT, "Arial");
}

void CreateDashboard()
{
    // Widened background (XSIZE = 340) to prevent text overflow shown in image
    ObjectCreate(0, "Dash_BG", OBJ_RECTANGLE_LABEL, 0, 0, 0);
    ObjectSetInteger(0, "Dash_BG", OBJPROP_XDISTANCE, 20);
    ObjectSetInteger(0, "Dash_BG", OBJPROP_YDISTANCE, 20);
    ObjectSetInteger(0, "Dash_BG", OBJPROP_XSIZE, 340); 
    ObjectSetInteger(0, "Dash_BG", OBJPROP_YSIZE, 230); // Taller to fit button
    ObjectSetInteger(0, "Dash_BG", OBJPROP_BGCOLOR, clrBlack);
    ObjectSetInteger(0, "Dash_BG", OBJPROP_COLOR, clrDarkGray);
    ObjectSetInteger(0, "Dash_BG", OBJPROP_BORDER_TYPE, BORDER_FLAT);
    ObjectSetInteger(0, "Dash_BG", OBJPROP_CORNER, CORNER_LEFT_UPPER);

    CreateLabel("Dash_Title", 30, 30, "MT5 GRID EA DASHBOARD", clrWhite);
    CreateLabel("Dash_ATR", 30, 50, "ATR: WAITING", clrYellow);
    CreateLabel("Dash_ADX", 30, 70, "ADX: WAITING", clrYellow);
    CreateLabel("Dash_Seq", 30, 90, "Layers Active (B/S): 0 / 0", clrLightGray);
    CreateLabel("Dash_FloatB", 30, 110, "BUY PnL: $0.00", clrLightGray);
    CreateLabel("Dash_FloatS", 30, 130, "SELL PnL: $0.00", clrLightGray);
    CreateLabel("Dash_Lots", 30, 150, "Total Lots (B/S): 0.00 / 0.00", clrLightGray);
    CreateLabel("Dash_Target", 30, 170, "Target (B/S): $2 / $2", clrLightGray);

    // Create the Start/Stop Button
    ObjectCreate(0, "Dash_Btn_StartStop", OBJ_BUTTON, 0, 0, 0);
    ObjectSetInteger(0, "Dash_Btn_StartStop", OBJPROP_XDISTANCE, 30);
    ObjectSetInteger(0, "Dash_Btn_StartStop", OBJPROP_YDISTANCE, 195);
    ObjectSetInteger(0, "Dash_Btn_StartStop", OBJPROP_XSIZE, 120);
    ObjectSetInteger(0, "Dash_Btn_StartStop", OBJPROP_YSIZE, 22);
    ObjectSetString(0, "Dash_Btn_StartStop", OBJPROP_FONT, "Arial");
    ObjectSetInteger(0, "Dash_Btn_StartStop", OBJPROP_FONTSIZE, 9);
    ObjectSetInteger(0, "Dash_Btn_StartStop", OBJPROP_CORNER, CORNER_LEFT_UPPER);
}

void UpdateDashboard()
{
    string statusText = "RUNNING";
    color statusClr = clrLimeGreen;
    
    // Update Button UI based on Manual Pause state
    if(ManualPause)
    {
        ObjectSetString(0, "Dash_Btn_StartStop", OBJPROP_TEXT, "START BOT");
        ObjectSetInteger(0, "Dash_Btn_StartStop", OBJPROP_BGCOLOR, clrLimeGreen);
        ObjectSetInteger(0, "Dash_Btn_StartStop", OBJPROP_COLOR, clrBlack);
    }
    else
    {
        ObjectSetString(0, "Dash_Btn_StartStop", OBJPROP_TEXT, "STOP BOT");
        ObjectSetInteger(0, "Dash_Btn_StartStop", OBJPROP_BGCOLOR, clrRed);
        ObjectSetInteger(0, "Dash_Btn_StartStop", OBJPROP_COLOR, clrWhite);
    }

    // Determine Logic State Text
    if(ManualPause)
    {
        statusText = "MANUALLY STOPPED";
        statusClr = clrRed;
    }
    else if(EmergencyCloseTriggered)
    {
        statusText = "!!! FORCE CLOSING !!!";
        statusClr = clrMagenta;
    }
    else if(AutoEmergencyPause)
    {
        statusText = "AUTO-PAUSED (WAITING FOR DROP)";
        statusClr = clrOrange;
    }
    else if(IsGridSuspended)
    {
        statusText = "OBSERVE (NO NEW LAYERS)";
        statusClr = clrYellow;
    }
    
    // Update ATR Label
    if(VolatilityFilter == FILTER_ATR || VolatilityFilter == FILTER_BOTH)
        ObjectSetString(0, "Dash_ATR", OBJPROP_TEXT, StringFormat("ATR (%d): %.1f Pts [%s]", ATR_Period, currentATR, statusText));
    else
        ObjectSetString(0, "Dash_ATR", OBJPROP_TEXT, "ATR: DISABLED");
    ObjectSetInteger(0, "Dash_ATR", OBJPROP_COLOR, (long)statusClr);

    // Update ADX Label
    if(VolatilityFilter == FILTER_ADX || VolatilityFilter == FILTER_BOTH)
        ObjectSetString(0, "Dash_ADX", OBJPROP_TEXT, StringFormat("ADX (%d): %.2f [%s]", ADX_Period, currentADX, statusText));
    else
        ObjectSetString(0, "Dash_ADX", OBJPROP_TEXT, "ADX: DISABLED");
    ObjectSetInteger(0, "Dash_ADX", OBJPROP_COLOR, (long)statusClr);

    ObjectSetString(0, "Dash_Seq", OBJPROP_TEXT, StringFormat("Layers Active (B/S): %d / %d", BuyPositions, SellPositions));
    
    color floatClrB = (BuyProfit >= 0) ? clrLimeGreen : clrRed;
    ObjectSetString(0, "Dash_FloatB", OBJPROP_TEXT, StringFormat("BUY PnL: $%.2f", BuyProfit));
    ObjectSetInteger(0, "Dash_FloatB", OBJPROP_COLOR, (long)floatClrB);
    
    color floatClrS = (SellProfit >= 0) ? clrLimeGreen : clrRed;
    ObjectSetString(0, "Dash_FloatS", OBJPROP_TEXT, StringFormat("SELL PnL: $%.2f", SellProfit));
    ObjectSetInteger(0, "Dash_FloatS", OBJPROP_COLOR, (long)floatClrS);
    
    ObjectSetString(0, "Dash_Lots", OBJPROP_TEXT, StringFormat("Total Lots (B/S): %.2f / %.2f", BuyTotalLots, SellTotalLots));
    ObjectSetString(0, "Dash_Target", OBJPROP_TEXT, StringFormat("Target (B/S): $%.2f / $%.2f", CurrentBuyTarget, CurrentSellTarget));
    
    ChartRedraw(0);
}
//+------------------------------------------------------------------+